# coding: utf-8

"""
    Calculator - OpenAPI 3.0

    Calculator for simple arthmetic funcions  # noqa: E501

    OpenAPI spec version: 1.0.11
    Contact: igoor.urbanowicz@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.resoult import Resoult  # noqa: E501
from swagger_client.rest import ApiException


class TestResoult(unittest.TestCase):
    """Resoult unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResoult(self):
        """Test Resoult"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.resoult.Resoult()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
