
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftADDSUBleftMULDIVMODrightNEGPOWADD COM DIV LPR MOD MUL NUM POW RPR SUBSTAR : EXPRSTAR : COMNUMR : NUMNUMR : SUB NUM %prec NEGEXPR : EXPR ADD EXPREXPR : EXPR SUB EXPREXPR : EXPR MUL EXPREXPR : EXPR DIV EXPREXPR : EXPR MOD EXPREXPR : EXPR POW EXPR2EXPR : LPR EXPR RPREXPR : NUMREXPR : SUB LPR EXPR RPR %prec NEGNUMR2 : NUMNUMR2 : SUB NUM %prec NEGEXPR2 : EXPR2 ADD EXPR2EXPR2 : EXPR2 SUB EXPR2EXPR2 : EXPR2 MUL EXPR2EXPR2 : EXPR2 DIV EXPR2EXPR2 : EXPR2 MOD EXPR2EXPR2 : LPR EXPR2 RPREXPR2 : NUMR2EXPR2 : SUB LPR EXPR2 RPR %prec NEG'
    
_lr_action_items = {'COM':([0,],[3,]),'LPR':([0,4,5,8,9,10,11,12,13,14,23,24,29,30,31,32,33,34,],[5,14,5,5,5,5,5,5,24,5,34,24,24,24,24,24,24,24,]),'SUB':([0,2,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,],[4,9,4,-12,-3,4,4,4,4,4,23,4,-4,9,-5,-6,-7,-8,-9,-10,23,-22,-14,9,-11,23,23,23,23,23,23,-15,30,-13,-16,-17,-18,-19,-20,30,-21,-23,]),'NUM':([0,4,5,8,9,10,11,12,13,14,23,24,29,30,31,32,33,34,],[7,15,7,7,7,7,7,7,26,7,35,26,26,26,26,26,26,26,]),'$end':([1,2,3,6,7,15,17,18,19,20,21,22,25,26,28,35,37,38,39,40,41,42,44,45,],[0,-1,-2,-12,-3,-4,-5,-6,-7,-8,-9,-10,-22,-14,-11,-15,-13,-16,-17,-18,-19,-20,-21,-23,]),'ADD':([2,6,7,15,16,17,18,19,20,21,22,25,26,27,28,35,36,37,38,39,40,41,42,43,44,45,],[8,-12,-3,-4,8,-5,-6,-7,-8,-9,-10,-22,-14,8,-11,-15,29,-13,-16,-17,-18,-19,-20,29,-21,-23,]),'MUL':([2,6,7,15,16,17,18,19,20,21,22,25,26,27,28,35,36,37,38,39,40,41,42,43,44,45,],[10,-12,-3,-4,10,10,10,-7,-8,-9,-10,-22,-14,10,-11,-15,31,-13,31,31,-18,-19,-20,31,-21,-23,]),'DIV':([2,6,7,15,16,17,18,19,20,21,22,25,26,27,28,35,36,37,38,39,40,41,42,43,44,45,],[11,-12,-3,-4,11,11,11,-7,-8,-9,-10,-22,-14,11,-11,-15,32,-13,32,32,-18,-19,-20,32,-21,-23,]),'MOD':([2,6,7,15,16,17,18,19,20,21,22,25,26,27,28,35,36,37,38,39,40,41,42,43,44,45,],[12,-12,-3,-4,12,12,12,-7,-8,-9,-10,-22,-14,12,-11,-15,33,-13,33,33,-18,-19,-20,33,-21,-23,]),'POW':([2,6,7,15,16,17,18,19,20,21,22,25,26,27,28,35,37,38,39,40,41,42,44,45,],[13,-12,-3,-4,13,13,13,13,13,13,-10,-22,-14,13,-11,-15,-13,-16,-17,-18,-19,-20,-21,-23,]),'RPR':([6,7,15,16,17,18,19,20,21,22,25,26,27,28,35,36,37,38,39,40,41,42,43,44,45,],[-12,-3,-4,28,-5,-6,-7,-8,-9,-10,-22,-14,37,-11,-15,44,-13,-16,-17,-18,-19,-20,45,-21,-23,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'STAR':([0,],[1,]),'EXPR':([0,5,8,9,10,11,12,14,],[2,16,17,18,19,20,21,27,]),'NUMR':([0,5,8,9,10,11,12,14,],[6,6,6,6,6,6,6,6,]),'EXPR2':([13,24,29,30,31,32,33,34,],[22,36,38,39,40,41,42,43,]),'NUMR2':([13,24,29,30,31,32,33,34,],[25,25,25,25,25,25,25,25,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> STAR","S'",1,None,None,None),
  ('STAR -> EXPR','STAR',1,'p_STAR_EXPR','parser.py',131),
  ('STAR -> COM','STAR',1,'p_STAR_COM','parser.py',137),
  ('NUMR -> NUM','NUMR',1,'p_NUMR','parser.py',142),
  ('NUMR -> SUB NUM','NUMR',2,'p_NUMR_NEG','parser.py',148),
  ('EXPR -> EXPR ADD EXPR','EXPR',3,'p_EXPR_ADD','parser.py',154),
  ('EXPR -> EXPR SUB EXPR','EXPR',3,'p_EXPR_SUB','parser.py',160),
  ('EXPR -> EXPR MUL EXPR','EXPR',3,'p_EXPR_MUL','parser.py',166),
  ('EXPR -> EXPR DIV EXPR','EXPR',3,'p_EXPR_DIV','parser.py',172),
  ('EXPR -> EXPR MOD EXPR','EXPR',3,'p_EXPR_MOD','parser.py',183),
  ('EXPR -> EXPR POW EXPR2','EXPR',3,'p_EXPR_POW','parser.py',193),
  ('EXPR -> LPR EXPR RPR','EXPR',3,'p_EXPR_PRS','parser.py',202),
  ('EXPR -> NUMR','EXPR',1,'p_EXPR_NUM','parser.py',207),
  ('EXPR -> SUB LPR EXPR RPR','EXPR',4,'p_EXPR_NEG_PRS','parser.py',211),
  ('NUMR2 -> NUM','NUMR2',1,'p_NUMR2','parser.py',218),
  ('NUMR2 -> SUB NUM','NUMR2',2,'p_NUMR2_NEG','parser.py',224),
  ('EXPR2 -> EXPR2 ADD EXPR2','EXPR2',3,'p_EXPR2_ADD','parser.py',230),
  ('EXPR2 -> EXPR2 SUB EXPR2','EXPR2',3,'p_EXPR2_SUB','parser.py',236),
  ('EXPR2 -> EXPR2 MUL EXPR2','EXPR2',3,'p_EXPR2_MUL','parser.py',242),
  ('EXPR2 -> EXPR2 DIV EXPR2','EXPR2',3,'p_EXPR2_DIV','parser.py',247),
  ('EXPR2 -> EXPR2 MOD EXPR2','EXPR2',3,'p_EXPR2_MOD','parser.py',260),
  ('EXPR2 -> LPR EXPR2 RPR','EXPR2',3,'p_EXPR2_PRS','parser.py',271),
  ('EXPR2 -> NUMR2','EXPR2',1,'p_EXPR2_NUM','parser.py',276),
  ('EXPR2 -> SUB LPR EXPR2 RPR','EXPR2',4,'p_EXPR2_NEG_PRS','parser.py',281),
]
