# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Resoult(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, res: int=None):  # noqa: E501
        """Resoult - a model defined in Swagger

        :param res: The res of this Resoult.  # noqa: E501
        :type res: int
        """
        self.swagger_types = {
            'res': int
        }

        self.attribute_map = {
            'res': 'res'
        }
        self._res = res

    @classmethod
    def from_dict(cls, dikt) -> 'Resoult':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The resoult of this Resoult.  # noqa: E501
        :rtype: Resoult
        """
        return util.deserialize_model(dikt, cls)

    @property
    def res(self) -> int:
        """Gets the res of this Resoult.


        :return: The res of this Resoult.
        :rtype: int
        """
        return self._res

    @res.setter
    def res(self, res: int):
        """Sets the res of this Resoult.


        :param res: The res of this Resoult.
        :type res: int
        """
        if res is None:
            raise ValueError("Invalid value for `res`, must not be `None`")  # noqa: E501

        self._res = res
