# coding: utf-8

# flake8: noqa
"""
    Calculator - OpenAPI 3.0

    Calculator for simple arthmetic funcions  # noqa: E501

    OpenAPI spec version: 1.0.11
    Contact: igoor.urbanowicz@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.expresions import Expresions
from swagger_client.models.resoult import Resoult
