# coding: utf-8

"""
    Calculator - OpenAPI 3.0

    Calculator for simple arthmetic funcions  # noqa: E501

    OpenAPI spec version: 1.0.11
    Contact: igoor.urbanowicz@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Expresions(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'num': 'int',
        'exp': 'str',
        'acc': 'int'
    }

    attribute_map = {
        'num': 'num',
        'exp': 'exp',
        'acc': 'acc'
    }

    def __init__(self, num=None, exp=None, acc=None):  # noqa: E501
        """Expresions - a model defined in Swagger"""  # noqa: E501
        self._num = None
        self._exp = None
        self._acc = None
        self.discriminator = None
        self.num = num
        self.exp = exp
        self.acc = acc

    @property
    def num(self):
        """Gets the num of this Expresions.  # noqa: E501


        :return: The num of this Expresions.  # noqa: E501
        :rtype: int
        """
        return self._num

    @num.setter
    def num(self, num):
        """Sets the num of this Expresions.


        :param num: The num of this Expresions.  # noqa: E501
        :type: int
        """
        if num is None:
            raise ValueError("Invalid value for `num`, must not be `None`")  # noqa: E501

        self._num = num

    @property
    def exp(self):
        """Gets the exp of this Expresions.  # noqa: E501


        :return: The exp of this Expresions.  # noqa: E501
        :rtype: str
        """
        return self._exp

    @exp.setter
    def exp(self, exp):
        """Sets the exp of this Expresions.


        :param exp: The exp of this Expresions.  # noqa: E501
        :type: str
        """
        if exp is None:
            raise ValueError("Invalid value for `exp`, must not be `None`")  # noqa: E501

        self._exp = exp

    @property
    def acc(self):
        """Gets the acc of this Expresions.  # noqa: E501


        :return: The acc of this Expresions.  # noqa: E501
        :rtype: int
        """
        return self._acc

    @acc.setter
    def acc(self, acc):
        """Sets the acc of this Expresions.


        :param acc: The acc of this Expresions.  # noqa: E501
        :type: int
        """
        if acc is None:
            raise ValueError("Invalid value for `acc`, must not be `None`")  # noqa: E501

        self._acc = acc

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Expresions, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Expresions):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
